env:
  STORAGE_ACCOUNT_NAME: "perkupstorage"

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Debug AZURE_CREDENTIALS
        run: |
          echo "AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}"

      - name: Login to Azure
        run: |
          AZURE_CREDENTIALS="${{ secrets.AZURE_CREDENTIALS }}"
          CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r '.clientId')
          CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r '.clientSecret')
          TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r '.tenantId')
          az login --service-principal --username $CLIENT_ID --password $CLIENT_SECRET --tenant $TENANT_ID

      - name: Upload to Azure Storage
        run: |
          az storage blob upload-batch --destination \$web --source . --account-name $STORAGE_ACCOUNT_NAME
