name: Azure Web Deploy

# Trigger this workflow whenever code is pushed to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Use Ubuntu runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Azure CLI for Azure commands
      - name: Set up Azure CLI
        uses: azure/cli-action@v1

      # Step 3: Azure login using service principal and secrets stored in GitHub Secrets
      - name: Azure login
        uses: azure/login@v1
        with:
          clientId: ${{ secrets.AZURE_CLIENT_ID }} # Azure service principal client ID
          clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }} # Azure service principal client secret
          tenantId: ${{ secrets.AZURE_TENANT_ID }} # Azure tenant ID
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Azure subscription ID

      # Step 4: Upload content to Azure Blob Storage using Azure CLI
      - name: Upload to Azure Blob Storage
        run: |
          # Using Azure CLI to upload content from the static_website folder to Azure Blob Storage
          az storage blob upload-batch \
            -d '$web' \
            --account-name perkupstorage \
            --source ./static_website \
            --overwrite true  # Overwrite existing files in Azure if they are updated

      # Step 5: Notify success
      - name: Deployment Successful
        run: echo "Deployment to Azure Storage Account completed successfully!"
