name: Azure Web Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure login
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo $AZURE_CREDENTIALS | jq
          CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r '.clientId')
          CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r '.clientSecret')
          TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r '.tenantId')
          SUBSCRIPTION_ID=$(echo $AZURE_CREDENTIALS | jq -r '.subscriptionId')
          echo "Client ID: $CLIENT_ID"
          echo "Tenant ID: $TENANT_ID"
          echo "Subscription ID: $SUBSCRIPTION_ID"
          az login --service-principal --username $CLIENT_ID --password $CLIENT_SECRET --tenant $TENANT_ID
          az account set --subscription $SUBSCRIPTION_ID

      - name: Upload to Azure Blob Storage
        run: |
          az storage blob upload \
            --container-name '$web' \
            --account-name perkupstorage \
            --name home.html \
            --file ./home.html \
            --overwrite

      - name: Deployment Successful
        run: echo "Deployment to Azure Storage Account completed successfully!"
