name: Deploy to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Azure CLI
        uses: azure/CLI@v1

      - name: Login to Azure
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_credentials.json
          az login --service-principal --username ${{ secrets.CLIENT_ID }} --password ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}

      - name: Upload to Azure Storage
        run: |
          az storage blob upload-batch -d \$web -s . --account-name perkupstorage
